#!/usr/bin/env bash
# Cloud terminal (ttyd + tmux) — web-based terminal with persistent sessions
#
# Must be invoked as root (typically via services/install.sh from
# base-setup/setup.sh). The ttyd service runs as SERVICE_USER (default
# agnostic-user) so browser shells land in the login user's account.
#
# ttyd launches /usr/local/bin/ttyd-tmux.sh which wraps zsh in a named
# tmux server (socket "attlas"). Browser connections attach to the
# "main" session by default, or to any session passed via ?arg=<name>
# thanks to ttyd --url-arg. When the browser disconnects the tmux
# server keeps running, so shells survive internet drops / laptop
# closes / etc. The dashboard's terminal detail page lists, creates,
# and kills sessions via `sudo -u agnostic-user tmux -L attlas …`,
# authorized by /etc/sudoers.d/alive-svc-tmux below.
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: install-terminal.sh must run as root." >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SERVICE_USER="${SERVICE_USER:-agnostic-user}"
SERVICE_HOME="$(getent passwd "${SERVICE_USER}" | cut -d: -f6)"

if [[ -z "${SERVICE_HOME}" || ! -d "${SERVICE_HOME}" ]]; then
  echo "ERROR: home directory for ${SERVICE_USER} not found." >&2
  exit 1
fi

# tmux is normally installed by base-setup/setup.sh, but guard against
# a trimmed-down provision path that skipped it.
if ! command -v tmux &>/dev/null; then
  echo "Installing tmux..."
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq tmux
fi
echo "tmux: $(tmux -V)"

# Install ttyd
if ! command -v ttyd &>/dev/null; then
  TTYD_VERSION="1.7.7"
  curl -fsSL "https://github.com/tsl0922/ttyd/releases/download/${TTYD_VERSION}/ttyd.x86_64" \
    -o /usr/local/bin/ttyd
  chmod +x /usr/local/bin/ttyd
fi
echo "ttyd: $(ttyd --version 2>&1 | head -1)"

# Deploy the tmux wrapper. Every browser connection execs this script,
# which in turn execs tmux new-session -A -s <arg1 or main>.
install -m 0755 "$SCRIPT_DIR/ttyd-tmux.sh" /usr/local/bin/ttyd-tmux.sh

# Create systemd unit
# WorkingDirectory drops the user into the iapetus workspace by default
# when they open /terminal in the browser. The path is hardcoded (not %h)
# because for system units %h resolves to /root regardless of User=.
#
# --url-arg: lets the client pass ?arg=<session-name> in the URL, which
# ttyd appends to the command. The wrapper sanitizes the value so this
# is safe even though the endpoint sits behind OAuth auth.
cat > /etc/systemd/system/ttyd.service <<UNIT
[Unit]
Description=ttyd - Web terminal (tmux-backed)
After=network.target

[Service]
Type=simple
User=${SERVICE_USER}
WorkingDirectory=${SERVICE_HOME}/iapetus
ExecStart=/usr/local/bin/ttyd --base-path /terminal --port 7681 --writable --url-arg -t titleFixed=attlas /usr/local/bin/ttyd-tmux.sh
Restart=always
RestartSec=5

# KillMode=process is load-bearing. The default control-group kill
# would terminate the double-forked tmux server process along with
# ttyd itself on restart/stop, wiping every persistent session. By
# killing only the main PID (ttyd) on unit stop, the tmux server —
# which already detached to its own session via setsid() — keeps
# running and all user sessions survive ttyd restarts and re-installs.
KillMode=process

[Install]
WantedBy=multi-user.target
UNIT

# Sudoers drop-in: let alive-svc (the dashboard) run tmux as the
# terminal's SERVICE_USER so the detail page can list, create, and
# kill sessions on the shared -L attlas socket. Scoped to a single
# binary + target user. Without this the dashboard can't see sessions
# because tmux sockets live under /tmp/tmux-<uid>/ with mode 700.
echo "Installing sudoers drop-in for alive-svc → tmux..."
cat > /etc/sudoers.d/alive-svc-tmux <<SUDOERS
# Auto-generated by services/install-terminal.sh — do not edit.
alive-svc ALL=(${SERVICE_USER}) NOPASSWD: /usr/bin/tmux
SUDOERS
chmod 440 /etc/sudoers.d/alive-svc-tmux
visudo -c -f /etc/sudoers.d/alive-svc-tmux

# Deploy Caddy route snippet
cp "$SCRIPT_DIR/terminal.caddy" /etc/caddy/conf.d/

# Start. Use enable + restart (not enable --now) so re-installs pick up
# unit-file changes — enable --now is a no-op when the service is already
# running and would leave the old process behind.
systemctl daemon-reload
systemctl enable ttyd
systemctl restart ttyd

# Nudge alive-server to re-read its public-path registry so the new
# terminal route is picked up without a full restart. Best-effort.
systemctl kill --signal=SIGHUP alive-server 2>/dev/null || true

echo "terminal installed -> /terminal (port 7681), tmux-backed, running as ${SERVICE_USER}"
