-- no-op: migration already applied to production database.
-- Original: ALTER TABLE entries ADD COLUMN content_human TEXT NOT NULL DEFAULT '';
-- Original: ALTER TABLE entries RENAME COLUMN content TO content_llm;
